import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <h1>Contact</h1>
      <br></br><br></br><br></br>
      <main>
     
      <div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
                Get in Touch

				</h2>
				<p>
                If you wanna get in touch, talk to me about a project collaboration or just say hi,
fill up the awesome<br></br> form below or send an email to

				</p>
				<p>
					<a class="btn btn-light btn-large" href="#"><strong>aminalaabidi2018@gmail.com</strong> </a>
				</p>
			</div>
		</div>
	</div>
</div>
<br></br> <br></br> 
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					 
					<button type="button" class="btn btn-outline-secondary">
                    <i class="fab fa-github"></i>Github
					</button>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					 
					<button type="button" class="btn btn-outline-info">
                    <i class="fab fa-linkedin"></i>Linkedin
					</button>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					 
					<button type="button" class="btn btn-outline-warning">
                    <i class="fas fa-phone-volume"></i> 20438696
					</button>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
	</div>
</div>
      
      <br></br><br></br>
      <br></br><br></br>
	  <br></br><br></br>
	  <div class="container">
	  <h2>
                Read my blogs in this website

				</h2>
				<p>
				People read blogs to learn something new.
By far,<br></br> the most common reason that people will read a blog post is to learn something new.
				</p>
		<br></br><br></br>
		<br></br><br></br>
		<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
			<a href="https://gomytech.gomycode.co/author/amina/">	<img src="/gomytech.png" width="150px" height="80px"></img></a>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					 
				<a href="https://aminalaabidi2018.medium.com/"><img src="/medium.png" width="150px" height="80px"></img></a>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-4">
				</div>
				<div class="col-md-4">
					 
			<a href="https://hashnode.com/@amina-up">	<img src="/hashnode.jpeg" width="150px" height="80px"></img></a>
				</div>
				<div class="col-md-4">
				</div>
			</div>
		</div>
	</div>
</div>
    
	
</div>
<br></br><br></br>
		
</main>
    </div>
	
  );
}
