import Link from "next/link";
import React from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Image from "next/image";

class About extends React.Component {
  render() {
    return (
      <div className={styles.container}>
        <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        </Head>
        <main className={styles.main}>
          <h1>Experience</h1>
        <div class="container">
	<div class="row">
		<div class="col-md-12">
			<img alt="Bootstrap Image Preview"  width="100px" height="100px" src="/simplo.svg" />
			<h3>
				Instructor
			</h3>
			<div class="tabbable" id="tabs-176521">
				<ul class="nav nav-tabs">
					<li class="nav-item">
						<a class="nav-link active" href="#tab1" data-toggle="tab">Monitoring</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#tab2" data-toggle="tab">Developer</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="tab1">
            <br></br>
            <ul>
              <li>
              Preparation of sets of exercises for each phase
              </li>
              <li>
              Preparation of sets of projects & challenges for each phase
              </li>
              <li>
              Monitoring the progress of learners

              </li>
              <li>
              Realization of different workshops
              </li>
            </ul>
					
           
					</div>
					<div class="tab-pane" id="tab2">
						<br></br>
            <ul>
              <li>
                Realisation applications FullStack
              </li>
              <li>
                Team work,Time management
              </li>
              <li>
                work with Agile scrum methodology
              </li>
            </ul>
					</div>
				</div>
			</div>
		</div>
	</div>
  <br></br><br></br><br></br>
	<div class="row">
		<div class="col-md-12">
			<img alt="Bootstrap Image Preview" width="80px" height="80px" src="/le152.png" />
      <br></br> <br></br>
			<h3>
				FullStack-Developer
			</h3>

			<div class="tabbable" id="tabs-24547">
				<ul class="nav nav-tabs">
					<li class="nav-item">
						<a class="nav-link active" href="#tab3" data-toggle="tab">Developer Fullstack</a>
					</li>
				
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="tab3">
            <br></br>
					<ul>
            <li>
              Places management reservations
            </li>
            <li>
               Work with Simplonien Team
            </li>
         
          </ul>
					</div>
					<div class="tab-pane" id="tab4">
						<p>
							Howdy, I'm in Section 2.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
        </main>
      </div>
    );
  }
}


export default About;
