import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Image from "next/image";
import Data from '../../data.json'
export default function projects(){
    return (
      <div className={styles.container}>
        <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        </Head>
        <h1> Projects</h1>
        <p  class="text-center">
From Web Components and UI/UX animations to React.JS, Redux, Vue.JS, and Node.JS.
 Check out my latest web software development portfolio projects.</p>
        <div className={styles.holeProjects}>
          {Data.map((projectsDetails, index) => {
            return (
              <div key={projectsDetails.id} className={styles.projects}>
                <Image
                  src={projectsDetails.image}
                  layout="intrinsic"
                  height={200}
                  width={300}
                  alt="Elif Shafak Author"
                />
                <h4>{projectsDetails.name}</h4>
                <p>{projectsDetails.description} </p>
                <p>Releasing date: {projectsDetails.Releasing_Date}</p>
               <br></br>
            <div className="d-flex justify-content-evenly">

             <div><i class="fab fa-html5 fa-2x " ></i></div>  
                <div><i class="fab fa-css3-alt fa-2x "></i></div>
                <div><i class="fab fa-react fa-2x fa-spin"></i></div>
                <div><i class="fab fa-node fa-2x "></i></div>
                <div><i class="fab fa-bootstrap fa-2x "></i></div>
                <div> <i class="fab fa-mdb fa-2x "></i></div>
               
                  </div>
               

                    
                <a class="badge bg-secondary text-white" href={projectsDetails.link}>Voir Github</a>
               

              </div>
            );
          })}
        </div>
      </div>
    );
  }
