import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function TrainingSkills() {
  return (
    <div className={styles.container}>
      <Head>
      <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">
          Training & Skills <br />
        </h1>
      
        <div className={styles.newestOne}>
          <div className="row container d-flex align-items-center">
            <div className="col-md-3 text-center">
              <Image
                src="/gomycode.png"
                layout="responsive"
                height={250}
                width={300}
              />
            </div>
            <div className="col-md-9 mt-4">
              <p>
                <strong>School :</strong> GOMYCODE
              </p>
              <p>
            

                <strong>Certification :</strong>   FULL STACK JS DEVELOPER - MERN STACK |
              </p>
              <p>
                <strong>Periode:</strong> October - 2020
              </p>
              <p className="text-justify">
                <strong>Description :</strong> FULL-TIME WEB DEVELOPEMENT
BOOTCAMP BASED ON AN ACTIVE PEDAGOGY
              </p>
             
            </div>
          </div>
        </div>
      </main>
      <main className={styles.main}>
     
        <div className={styles.coming}>
         
        </div> 
        
           <div className="d-flex justify-content-around flex-wrap">
           <div>
            <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Front-End</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
    <th scope="row">Html5</th>
    <td>Css </td>
      <td>Javascript</td>
      <td>Php</td>
    </tr>
    <tr>
      <th>React js</th>
      <td>Nextjs</td>
      <td>Vuejs</td>
      <td>Graphql</td>
    </tr>
    <tr>
      <th scope="row">Nextjs</th>
      <td colspan="2">Bootstrap</td>
      <td>Css</td>
    </tr>
  </tbody>
</table>
</div>  
<div>
            <table class="table table-secondary table-striped">
  <thead>
    <tr>
      <th scope="col">Back-End </th>
      <th> database</th>
    
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">MySQL</th>
      <td></td>
      <td>MongoDb</td>
      <td></td>
      
    </tr>
    <tr>
      <td scope="row"></td>
      <td>Xamp</td>
      <td></td>
      <td>Wamp</td>
    </tr>
    <tr>
      <th scope="row">Express js</th>
      <td colspan="2"></td>
      <td>Node js</td>
    </tr>
  </tbody>
</table>
</div>  
<div>
            <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Other</th>
  
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Agile Scrum</th>
      <td></td>
      <td>problem solving</td>
      <td></td>
      
    </tr>
    <tr>
      <th scope="row"></th>
      <td>wordpress</td>
      <td></td>
      <td>adobe xd</td>
    </tr>
    <tr>
      <th scope="row">Git</th>
      <td colspan="2"></td>
      <td>github</td>
    </tr>
  </tbody>
</table>
</div>

</div>    
          
      </main>
    </div>
  );
}
